# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-01 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recko_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='family_id',
            new_name='family',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='universe_id',
            new_name='universe',
        ),
    ]
