# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-01 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recko_api', '0002_auto_20181201_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fname', to='recko_api.family'),
        ),
        migrations.AlterField(
            model_name='person',
            name='universe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uname', to='recko_api.universe'),
        ),
    ]
