# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-01 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recko_api', '0003_auto_20181201_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='power',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
