# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-02 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recko_api', '0006_auto_20181202_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
